<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ChromeTest"
           tests="13"
           failures="2"
           errors="0"
           skipped="0"
           time="163.648">
  <properties />
            <testcase name="createNewCustomerGmailPlus" time="17.369" classname="automationFramework.TestCases.CreateCustomerTest">
                <failure type="java.lang.AssertionError"
                  message="expected [7033322717] but found [7033322717,undefined,undefined]"
              >
<![CDATA[java.lang.AssertionError: expected [7033322717] but found [7033322717,undefined,undefined]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.TestCases.CreateCustomerTest.createNewCustomerGmailPlus(CreateCustomerTest.java:357)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="createNewCustomer" time="15.503" classname="automationFramework.TestCases.CreateCustomerTest">
                <failure type="java.lang.AssertionError"
                  message="expected [7511171754] but found [7511171754,undefined,undefined]"
              >
<![CDATA[java.lang.AssertionError: expected [7511171754] but found [7511171754,undefined,undefined]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.TestCases.CreateCustomerTest.createNewCustomer(CreateCustomerTest.java:62)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="createCustomerEmailMissing" time="7.578" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerCancel" time="10.322" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerInvalidPin" time="12.711" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerInvalidPin2" time="13.738" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerContactTypeNotSelected" time="10.574" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerNameMissing" time="7.378" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerInvalidUserName" time="11.554" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerPostalCodeMissing" time="13.141" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerDuplicateUserName" time="23.634" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerInvalidEmail" time="12.490" classname="automationFramework.TestCases.CreateCustomerTest" />
                <testcase name="createCustomerInvalidPhone" time="7.656" classname="automationFramework.TestCases.CreateCustomerTest" />
      
</testsuite>
