<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NACTS-081729" name="automationFramework.TestCases.CreateCustomerTest" tests="13" failures="0" timestamp="27 Apr 2017 18:41:58 GMT" time="193.130" errors="2">
  <testcase name="createCustomerInvalidUserName" time="13.731" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerNameMissing" time="9.638" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerPostalCodeMissing" time="15.589" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidEmail" time="14.727" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerEmailMissing" time="9.810" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerCancel" time="12.565" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerDuplicateUserName" time="25.816" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidPhone" time="9.989" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerContactTypeNotSelected" time="12.801" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createNewCustomerGmailPlus" time="19.579" classname="automationFramework.TestCases.CreateCustomerTest">
    <error type="java.lang.AssertionError" message="expected [7033322717] but found [7033322717,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [7033322717] but found [7033322717,undefined,undefined]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.CreateCustomerTest.createNewCustomerGmailPlus(CreateCustomerTest.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- createNewCustomerGmailPlus -->
  <testcase name="createCustomerInvalidPin" time="14.973" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createNewCustomer" time="17.908" classname="automationFramework.TestCases.CreateCustomerTest">
    <error type="java.lang.AssertionError" message="expected [7511171754] but found [7511171754,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [7511171754] but found [7511171754,undefined,undefined]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.CreateCustomerTest.createNewCustomer(CreateCustomerTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- createNewCustomer -->
  <testcase name="createCustomerInvalidPin2" time="16.004" classname="automationFramework.TestCases.CreateCustomerTest"/>
</testsuite> <!-- automationFramework.TestCases.CreateCustomerTest -->
